# Form implementation generated from reading ui file 'errorwindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ErrorWindow(object):
    def setupUi(self, ErrorWindow, message):
        ErrorWindow.setObjectName("ErrorWindow")
        ErrorWindow.resize(381, 149)
        self.error_icon = QtWidgets.QGraphicsView(parent=ErrorWindow)
        self.error_icon.setGeometry(QtCore.QRect(30, 30, 71, 61))
        self.error_icon.setObjectName("error_icon")
        self.label = QtWidgets.QLabel(parent=ErrorWindow)
        self.label.setGeometry(QtCore.QRect(130, 40, 211, 41))
        self.label.setObjectName("label")
        self.ok_button = QtWidgets.QPushButton(parent=ErrorWindow)
        self.ok_button.setGeometry(QtCore.QRect(150, 100, 93, 28))
        self.ok_button.setObjectName("pushButton")

        self.retranslateUi(ErrorWindow)
        QtCore.QMetaObject.connectSlotsByName(ErrorWindow)
        self.ErrorWindow = ErrorWindow
        self.ok_button.clicked.connect(self.ok_clicked)
        self.label.setText(message)

    def retranslateUi(self, ErrorWindow):
        _translate = QtCore.QCoreApplication.translate
        ErrorWindow.setWindowTitle(_translate("ErrorWindow", "Error"))
        self.label.setText(_translate("ErrorWindow", "Error message"))
        self.ok_button.setText(_translate("ErrorWindow", "OK"))

    def ok_clicked(self):
        self.ErrorWindow.close()