# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from rk_comparison.interface.ui.plotting_options import Ui_PlottingOptions

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, controller):
        self.controller = controller

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(243, 240)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.input_button.setGeometry(QtCore.QRect(60, 40, 121, 51))
        self.input_button.setObjectName("input_button")
        self.calculate_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.calculate_button.setGeometry(QtCore.QRect(60, 130, 121, 51))
        self.calculate_button.setObjectName("calculate_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.input_button.clicked.connect(self.set_input)
        self.calculate_button.clicked.connect(self.start_calculations)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.input_button.setText(_translate("MainWindow", "Input Data"))
        self.calculate_button.setText(_translate("MainWindow", "Calculate"))

    def set_input(self):
        pass

    def start_calculations(self):
        self.controller.initialize(self.controller.id.get_t_min(),
                                   self.controller.id.get_dt(),
                                   self.controller.id.get_t_max(),
                                   self.controller.nd.get_nuclei(),
                                   self.controller.nd.get_tau(),
                                   self.controller.id.get_truth_table())
        self.controller.calculate()
        self.controller.calculate_analytical()
        self.controller.compare()

        self.popup = QtWidgets.QDialog()
        self.popup_ui = Ui_PlottingOptions()
        self.popup_ui.setupUi(self.popup, self.controller)
        self.popup.show()

