# Form implementation generated from reading ui file 'plotting_options.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PlottingOptions(object):
    def setupUi(self, PlottingOptions, controller):
        self.controller = controller

        PlottingOptions.setObjectName("PlottingOptions")
        PlottingOptions.resize(273, 229)
        self.plot_result = QtWidgets.QPushButton(parent=PlottingOptions)
        self.plot_result.setGeometry(QtCore.QRect(70, 30, 141, 51))
        self.plot_result.setObjectName("plot_result")
        self.plot_comparison = QtWidgets.QPushButton(parent=PlottingOptions)
        self.plot_comparison.setGeometry(QtCore.QRect(70, 120, 141, 51))
        self.plot_comparison.setObjectName("plot_comparison")

        self.retranslateUi(PlottingOptions)
        QtCore.QMetaObject.connectSlotsByName(PlottingOptions)

        self.plot_result.clicked.connect(self.plot_all_results)
        self.plot_comparison.clicked.connect(self.plot_all_comparison)

    def retranslateUi(self, PlottingOptions):
        _translate = QtCore.QCoreApplication.translate
        PlottingOptions.setWindowTitle(_translate("PlottingOptions", "PlottingOptions"))
        self.plot_result.setText(_translate("PlottingOptions", "Plot result"))
        self.plot_comparison.setText(_translate("PlottingOptions", "Plot comparison"))

    def plot_all_results(self):
        self.controller.plot(True, self.controller.results_rk, "Nuclear Decay [nuclei]", "Nuclear Decay")

    def plot_all_comparison(self):
        self.controller.plot(False, self.controller.compare_rk, "Analytical - RK [nuclei]", "RK Comparison")
