# Form implementation generated from reading ui file 'ui_errorwindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ErrorWindow(object):
    def setupUi(self, ErrorWindow):
        ErrorWindow.setObjectName("ErrorWindow")
        ErrorWindow.resize(344, 149)
        self.label = QtWidgets.QLabel(parent=ErrorWindow)
        self.label.setGeometry(QtCore.QRect(30, 10, 291, 91))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=ErrorWindow)
        self.pushButton.setGeometry(QtCore.QRect(120, 110, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(ErrorWindow)
        QtCore.QMetaObject.connectSlotsByName(ErrorWindow)

    def retranslateUi(self, ErrorWindow):
        _translate = QtCore.QCoreApplication.translate
        ErrorWindow.setWindowTitle(_translate("ErrorWindow", "Error"))
        self.label.setText(_translate("ErrorWindow", "Error message template"))
        self.pushButton.setText(_translate("ErrorWindow", "OK"))
