# Form implementation generated from reading ui file 'ui_plottingwindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PlottingWindow(object):
    def setupUi(self, PlottingWindow):
        PlottingWindow.setObjectName("PlottingWindow")
        PlottingWindow.resize(278, 278)
        self.plot_result = QtWidgets.QPushButton(parent=PlottingWindow)
        self.plot_result.setGeometry(QtCore.QRect(70, 30, 141, 51))
        self.plot_result.setObjectName("plot_result")
        self.plot_comparison = QtWidgets.QPushButton(parent=PlottingWindow)
        self.plot_comparison.setGeometry(QtCore.QRect(70, 110, 141, 51))
        self.plot_comparison.setObjectName("plot_comparison")
        self.cancel_button = QtWidgets.QPushButton(parent=PlottingWindow)
        self.cancel_button.setGeometry(QtCore.QRect(70, 190, 141, 51))
        self.cancel_button.setObjectName("cancel_button")

        self.retranslateUi(PlottingWindow)
        QtCore.QMetaObject.connectSlotsByName(PlottingWindow)

    def retranslateUi(self, PlottingWindow):
        _translate = QtCore.QCoreApplication.translate
        PlottingWindow.setWindowTitle(_translate("PlottingWindow", "Plotting"))
        self.plot_result.setText(_translate("PlottingWindow", "Plot result"))
        self.plot_comparison.setText(_translate("PlottingWindow", "Plot comparison"))
        self.cancel_button.setText(_translate("PlottingWindow", "Cancel"))
