# Form implementation generated from reading ui file 'ui_plottingwindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PlottingWindow(object):
    def setupUi(self, PlottingWindow):
        PlottingWindow.setObjectName("PlottingWindow")
        PlottingWindow.resize(880, 198)
        self.plot_result = QtWidgets.QPushButton(parent=PlottingWindow)
        self.plot_result.setGeometry(QtCore.QRect(30, 30, 141, 51))
        self.plot_result.setObjectName("plot_result")
        self.plot_comparison = QtWidgets.QPushButton(parent=PlottingWindow)
        self.plot_comparison.setGeometry(QtCore.QRect(200, 30, 141, 51))
        self.plot_comparison.setObjectName("plot_comparison")
        self.cancel_button = QtWidgets.QPushButton(parent=PlottingWindow)
        self.cancel_button.setGeometry(QtCore.QRect(460, 110, 141, 51))
        self.cancel_button.setObjectName("cancel_button")
        self.plot_min = QtWidgets.QPushButton(parent=PlottingWindow)
        self.plot_min.setGeometry(QtCore.QRect(370, 30, 141, 51))
        self.plot_min.setObjectName("plot_min")
        self.plot_mean = QtWidgets.QPushButton(parent=PlottingWindow)
        self.plot_mean.setGeometry(QtCore.QRect(710, 30, 141, 51))
        self.plot_mean.setObjectName("plot_mean")
        self.plot_max = QtWidgets.QPushButton(parent=PlottingWindow)
        self.plot_max.setGeometry(QtCore.QRect(540, 30, 141, 51))
        self.plot_max.setObjectName("plot_max")
        self.save_button = QtWidgets.QPushButton(parent=PlottingWindow)
        self.save_button.setGeometry(QtCore.QRect(280, 110, 141, 51))
        self.save_button.setObjectName("save_button")

        self.retranslateUi(PlottingWindow)
        QtCore.QMetaObject.connectSlotsByName(PlottingWindow)

    def retranslateUi(self, PlottingWindow):
        _translate = QtCore.QCoreApplication.translate
        PlottingWindow.setWindowTitle(_translate("PlottingWindow", "Plotting"))
        self.plot_result.setText(_translate("PlottingWindow", "Plot result"))
        self.plot_comparison.setText(_translate("PlottingWindow", "Plot comparison"))
        self.cancel_button.setText(_translate("PlottingWindow", "Cancel"))
        self.plot_min.setText(_translate("PlottingWindow", "Plot minimal values"))
        self.plot_mean.setText(_translate("PlottingWindow", "Plot mean values"))
        self.plot_max.setText(_translate("PlottingWindow", "Plot maximal values"))
        self.save_button.setText(_translate("PlottingWindow", "Save"))
